# Generated by Django 4.2.6 on 2024-10-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=50)),
                ('Autor', models.CharField(max_length=50)),
                ('Editorial', models.CharField(max_length=30)),
                ('Fecha_Publicacion', models.DateField()),
                ('Portada', models.ImageField(null=True, upload_to='Portadas')),
                ('Sinopsis', models.TextField(blank=True)),
                ('Precio', models.IntegerField()),
            ],
        ),
    ]
